FROM jenkins/jenkins:lts

USER root

# Install required tools
RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    jq \
    bc \
    curl \
    docker.io && \
    apt-get clean

# Give Jenkins access to Docker
RUN usermod -aG docker jenkins

USER jenkins